# Page tree
nav:
  - News: news.md
  - Overview: overview.md
  - Architecture: architecture.md
  - Prerequisites: prerequisites.md
  - Getting Started: getting-started.md
  - Features: features.md
  - CLI Reference: cli-reference.md
  - APIs: apis.md
  - Tutorials: tutorials.md
  - Operations and Troubleshooting: operations-and-troubleshooting.md
  - Contact and Support: contact-and-support.md

# Project information
site_name: test-test-30552532
site_url: https://pages.github.tools.sap/dxp/docs/
site_author: DXP team
site_description: The Developer Experience Portal Documentation

# Repository
repo_name: dxp/docs
repo_url: https://github.tools.sap/dxp/docs
edit_uri: ""

# Configuration
theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: indigo
  icon:
    logo: fontawesome/solid/code
  features:
    - navigation.tabs
docs_dir: docs
site_dir: docs-gen

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
